import type { Metadata } from "next";
import { Poppins } from "next/font/google"; // Importa a fonte do Google
import "./globals.css";

// Configura a fonte Poppins
const poppins = Poppins({
  subsets: ["latin"], // Subconjunto necessário para o suporte completo ao idioma
  variable: "--font-poppins", // Define uma variável CSS para a fonte
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Intervalo de pesos
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>{children}</body>
    </html>
  );
}
